version: "3.1"

volumes:
  postgresql-data:

services:
  database:
    image: postgis/postgis:15-master
    restart: on-failure
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: geojson_db
      POSTGRES_PASSWORD: postgres

  app:
    container_name: geojson_app
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: sh -c "./wait_db.sh localhost:5432 --
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - database
    restart: on-failure
