version: '2.1'
orbs:
  python: circleci/python@1.0.0
jobs:
  check_pep8:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            poetry run flake8 .
          name: Check pep8 format
workflows:
  main:
    jobs:
      - check_pep8