version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  pep8:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            poetry run flake8 .
          name: Check PEP8 format

workflows:
  version: 2
  quality:
    jobs:
      - pep8
