# Generated by Django 4.1.3 on 2022-11-30 02:34

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceArea",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("polygon", django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ("provider", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="providers.provider")),
            ],
        ),
    ]
